name: "ECOFLOW MQTT Adapter"
description: "connect to ecoflow MQTT and push data to local MQTT server"
version: "0.0.3"
slug: "ecoflow_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

ports:
  1883/tcp: 1883

options:
  key: "the_api_key"
  secret: "the_api_secret"
  sn: "the_device_serial_number"
  mqtthost: "mqtt.local"
  mqttport: "1883"
schema:
  key: str
  secret: str
  sn: str
  mqtthost: str
  mqttport: int